POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InByYWN0aWNlVXNlck5hbWUiLCJpZCI6IjY5YjM2Y2ZmNWIxMzEzODA3M2U5MDFjNyIsImlhdCI6MTc3MzYyNTE0Nn0.X4wOOqHZj4774BqUUx3X_ilZOzfIditf-zZmOPDOx34

{
    "title": "test3",
    "author": "test3",
    "url": "test3",
    "likes": 1
}